export function run(this:void):string[] {
  const cases:string[]=[];
  const check=(v:unknown,n:string):void=>{assert(v,n);cases.push(n);};
  const text="Привет\0VC";
  check(utf8.tostring(utf8.tobytes(text))===text,"UTF8 binary round trip");
  check(utf8.length("Привет")===6 && utf8.sub("Привет",2,3)==="ри","UTF8 inclusive character bounds");
  const compressed=compression.encode(utf8.tobytes(text));
  check(utf8.tostring(compression.decode(compressed))===text,"gzip round trip");
  const object=bjson.frombytes(bjson.tobytes({value:42}));
  check(typeof object==="object" && object!==null && (object as {value:unknown}).value===42,"binary JSON round trip");
  const [integer,flag]=byteutil.unpack("i?",byteutil.pack("i?",42,true));
  check(integer===42 && flag===true && byteutil.get_size("i?")===5,"binary multiple return");
  const parsed=xml.parse('<panel id="probe"><label>Text</label></panel>');
  check(parsed["#"]==="panel" && parsed.id==="probe" && xml.tostring(parsed).includes("Text"),"XML native node shape");
  check(crypto.features().api_version===crypto.API_VERSION,"crypto feature version");
  const digest=crypto.sha256("hello");
  check(base64.encode(utf8.tobytes(digest))==="LPJNul+wow4m6DsqxbninhsWHlwfp0JecwQzYpOLmCQ=","SHA256 raw binary output");
  const hash=crypto.hash_new("SHA256");hash.update("hel").update("lo");
  check(hash.final()===digest && hash.reset().update("hello").final()===digest,"streaming hash self/chaining");
  const [privateKey,publicKey]=crypto.ed25519_keypair();
  const signature=crypto.ed25519_sign(privateKey,"hello");
  const [valid]=crypto.ed25519_verify(publicKey,"hello",signature);
  const [invalid,error]=crypto.ed25519_verify(publicKey,"wrong",signature);
  check(valid===true && invalid===false && typeof error==="string","signature verify success/failure multiple return");
  const key=crypto.random_bytes(16),nonce=crypto.random_bytes(12);
  const ciphertext=crypto.aes_gcm_encrypt(key,nonce,"context",text);
  const [plain]=crypto.aes_gcm_decrypt(key,nonce,"context",ciphertext);
  const [bad,badError]=crypto.aes_gcm_decrypt(key,nonce,"wrong",ciphertext);
  check(plain===text && bad===undefined && typeof badError==="string","AES authenticated decrypt result shape");
  const rng=random.Random();rng.seed(42);const first=rng.random();rng.seed(42);
  check(first===rng.random(),"explicit Random seed repeatability");
  const stream=file.open("world:stream.bin","wb");stream.write(utf8.tobytes(text));stream.flush();stream.close();
  const inputStream=file.open("world:stream.bin","rb");const bytes=inputStream.read_fully() as VC.Bytearray;inputStream.close();
  check(utf8.tostring(bytes)===text,"engine file stream binary round trip");
  const camera=cameras.get("core:first-person");
  const zoom=camera.get_zoom();camera.set_zoom(zoom+0.25);
  check(camera.get_zoom()===zoom+0.25 && camera.get_index()===cameras.index(camera.get_name()),"camera wrapper and native ID");
  camera.set_zoom(zoom);
  const agent=pathfinding.create_agent();pathfinding.set_enabled(agent,true);pathfinding.set_max_visited(agent,64);pathfinding.set_jump_height(agent,1);
  check(pathfinding.is_enabled(agent) && pathfinding.remove_agent(agent) && !pathfinding.is_enabled(agent),"pathfinding agent lifecycle");
  check(audio.play_sound_2d("absent",1,1)===0 && !audio.is_playing(0),"headless audio failed playback ID");
  const [x,y,z]=audio.get_position(0);check(x===undefined&&y===undefined&&z===undefined,"absent speaker multiple nil");
  const pcm=audio.PCMStream(44100,1,16);pcm.feed(utf8.tobytes("\0\0"));pcm.share("probe:pcm");
  check(typeof pcm.feed==="function","PCM feed and headless share noop");
  return cases;
}
