export function run(this: void): string[] {
  const cases:string[]=[];
  const check=(value:unknown,name:string):void=>{assert(value,name);cases.push(name);};
  const map=Heightmap(4,3);
  check(map.width===4 && map.height===3 && map.at(0,0)===0,"Heightmap constructor/dimensions/zero initialization");
  map.noiseSeed=42; map.normalNoise=true;
  check(map.noiseSeed===undefined && map.normalNoise===undefined,"Heightmap setter-only properties read nil");
  map.add(2); map.pow(3); map.sub(1); map.mul(2); map.min(12); map.max(13);
  check(map.at(3,2)===13,"Heightmap scalar operations mutate in place");
  const other=Heightmap(4,3);other.add(3);
  map.add(other);map.sub(other);map.mul(other);map.min(other);map.max(other);map.pow(other);
  check(map.at(0,0)===27,"Heightmap map operations");
  map.mixin(3,0.5);check(map.at(0,0)===15,"Heightmap scalar mixin");
  map.mixin(other,0.5);check(map.at(0,0)===9,"Heightmap map mixin");
  const factor=Heightmap(4,3);factor.add(0.5);
  map.mixin(1,factor);map.mixin(other,factor);check(map.at(0,0)===4,"Heightmap map factor mixin");
  map.mul(-1);map.abs();map.sub(0.25);map.floor();map.add(0.5);map.round();map.add(0.25);map.ceil();
  check(map.at(0,0)===5,"Heightmap unary rounding");
  map.mul(0);map.sin();map.cos();map.tan();check(Math.abs(map.at(0,0)-Math.tan(1))<0.001,"Heightmap radians trig");
  map.resize(8,6,"nearest");map.crop(1,1,4,3);
  check(map.width===4 && map.height===3,"Heightmap resize/crop");
  const a=Heightmap(4,3),b=Heightmap(4,3);a.noiseSeed=42;b.noiseSeed=42;
  a.noise([100,200],0.5,2,0.3);b.noise([100,200],0.5,2,0.3);
  check(a.at(2,1)===b.at(2,1),"Heightmap deterministic noise seed");
  a.cellnoise([0,0],0.4);check(Number.isFinite(a.at(0,0)),"Heightmap cellular noise");
  a.dump("world:heightmap.png");check(file.length("world:heightmap.png")>0,"Heightmap PNG dump");
  check(generation.get_generators()["genprobe:typed"]!==undefined && typeof generation.get_default_generator()==="string","generator discovery");
  const stone=block.index("base:stone");
  check(block.get(2,100,2)===stone,"typed generator structure placement");
  check(block.get(0,10,0)===stone && block.get(0,100,0)===block.index("core:air"),"typed generator terrain height");
  block.set(4,105,4,stone);
  const fragment=generation.create_fragment([4,105,4],[4,105,4],false,false);
  check(fragment.size[0]===1 && fragment.size[1]===1 && fragment.size[2]===1,"VoxelFragment inclusive endpoints/size table");
  generation.save_fragment(fragment,"world:fragment.vox");
  const loaded=generation.load_fragment("world:fragment.vox");loaded.place([5,105,4],0);
  check(block.get(5,105,4)===stone,"VoxelFragment save/load/place");
  const fromBytes=generation.load_fragment(file.read_bytes("world:fragment.vox"));fromBytes.crop();fromBytes.place([6,105,4],3);
  check(block.get(6,105,4)===stone,"VoxelFragment Bytearray load/crop/rotation");
  return cases;
}
