'use strict';
// Minimal VSIX packager using ZIP's stored entries. No runtime/build dependencies.
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'../..'),pkg=require(path.join(root,'package.json'));
const files=[];
function add(name,data) {files.push({name,data:Buffer.isBuffer(data)?data:Buffer.from(data)});}
function walk(dir) {for(const ent of fs.readdirSync(path.join(root,dir),{withFileTypes:true})){const file=path.posix.join(dir,ent.name);if(ent.isDirectory())walk(file);else if(!file.endsWith('.map'))add('extension/'+file,fs.readFileSync(path.join(root,file)));}}
for(const dir of ['out/src','out/media','out/runtime','lua','luals','snippets','icons'])walk(dir);
for(const file of ['package.json','README.md','CHANGELOG.md','LICENSE','LICENSES.md'])add('extension/'+file,fs.readFileSync(path.join(root,file)));
add('[Content_Types].xml','<?xml version="1.0" encoding="utf-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="json" ContentType="application/json"/><Default Extension="wasm" ContentType="application/wasm"/><Default Extension="js" ContentType="application/javascript"/><Default Extension="lua" ContentType="text/plain"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="svg" ContentType="image/svg+xml"/><Default Extension="png" ContentType="image/png"/><Default Extension="txt" ContentType="text/plain"/><Default Extension="html" ContentType="text/html"/><Default Extension="css" ContentType="text/css"/><Default Extension="md" ContentType="text/markdown"/><Default Extension="vsixmanifest" ContentType="text/xml"/><Override PartName="/extension/LICENSE" ContentType="text/plain"/></Types>');
add('extension.vsixmanifest',`<?xml version="1.0" encoding="utf-8"?><PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011"><Metadata><Identity Language="en-US" Id="${pkg.name}" Version="${pkg.version}" Publisher="${pkg.publisher}"/><DisplayName>${pkg.displayName}</DisplayName><Description xml:space="preserve">${pkg.description}</Description><Categories>${pkg.categories.join(',')}</Categories><Tags>${pkg.keywords.join(',')}</Tags><Icon>extension/${pkg.icon}</Icon><License>extension/LICENSE</License><GalleryFlags>Public</GalleryFlags><Properties><Property Id="Microsoft.VisualStudio.Code.Engine" Value="${pkg.engines.vscode}"/><Property Id="Microsoft.VisualStudio.Code.ExtensionDependencies" Value="${(pkg.extensionDependencies || []).join(',')}"/><Property Id="Microsoft.VisualStudio.Code.ExtensionPack" Value=""/><Property Id="Microsoft.VisualStudio.Code.ExtensionKind" Value="workspace"/><Property Id="Microsoft.VisualStudio.Code.ExecutesCode" Value="true"/><Property Id="Microsoft.VisualStudio.Services.GitHubFlavoredMarkdown" Value="true"/><Property Id="Microsoft.VisualStudio.Services.Content.Pricing" Value="Free"/></Properties></Metadata><Installation><InstallationTarget Id="Microsoft.VisualStudio.Code"/></Installation><Dependencies/><Assets><Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true"/><Asset Type="Microsoft.VisualStudio.Services.Content.Details" Path="extension/README.md" Addressable="true"/><Asset Type="Microsoft.VisualStudio.Services.Content.Changelog" Path="extension/CHANGELOG.md" Addressable="true"/><Asset Type="Microsoft.VisualStudio.Services.Content.License" Path="extension/LICENSE" Addressable="true"/><Asset Type="Microsoft.VisualStudio.Services.Icons.Default" Path="extension/${pkg.icon}" Addressable="true"/></Assets></PackageManifest>`);
const table=Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
const crc=data=>{let n=0xffffffff;for(const b of data)n=table[(n^b)&255]^(n>>>8);return (n^0xffffffff)>>>0;};
const chunks=[],central=[];let offset=0;
for(const file of files){const name=Buffer.from(file.name),size=file.data.length,checksum=crc(file.data),header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt32LE(checksum,14);header.writeUInt32LE(size,18);header.writeUInt32LE(size,22);header.writeUInt16LE(name.length,26);chunks.push(header,name,file.data);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt32LE(checksum,16);c.writeUInt32LE(size,20);c.writeUInt32LE(size,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(offset,42);central.push(c,name);offset+=header.length+name.length+size;}
const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);
fs.mkdirSync(path.join(root,'dist'),{recursive:true});const target=path.join(root,'dist',`${pkg.name}-${pkg.version}.vsix`);fs.writeFileSync(target,Buffer.concat([...chunks,directory,end]));console.log(target);

export {};
