app.config_packs({"gamekit"})
app.new_world("vcts-smoke","42","gamekit:flat")
local pid=player.create("Template Test")
player.set_pos(pid,0,100,0)
app.set_setting("chunks.load-distance",2)
app.set_setting("chunks.load-speed",8)
app.sleep_until(function() return block.get(0,10,0)~=-1 end,10000,20)
assert(block.get(0,10,0)==block.index("gamekit:floor"),"own terrain not generated")
assert(not pack.is_installed("base"),"base pack leaked into standalone game")
app.sleep(0.25)
app.save_world()
local first=json.parse(file.read("world:gamekit-state.json"))
assert(first.version==1 and first.data.ticks>0,"typed lifecycle/scheduler/save did not run")
app.close_world(true)
app.open_world("vcts-smoke")
app.save_world()
local second=json.parse(file.read("world:gamekit-state.json"))
assert(second.data.ticks>=first.data.ticks,"saved state not restored")
file.write("world:probe.json",json.tostring({cases={"world callbacks","typed events","scoped timer","versioned save","world reload","own typed terrain","base pack excluded"},ticks=second.data.ticks,kind="game"}))
app.close_world(true)
print("VCTS_PROJECT_PASS")
