-- The graphical client already loads project.toml base packs.
app.new_world("vcts-preview", "42", "base:flat_grass")
player.set_pos(0,0,102,4)
player.set_flight(0,true)
app.sleep_until(function() return block.get(0,100,0)~=-1 end,10000,15)
local core = require("vcts:core")
local id = block.index("workshop:battery")
for x=-3,3 do
    for z=-2,5 do block.set(x,99,z,block.index("base:stone"),0) end
end
block.place(0,100,0,id,0,0)
block.place(2,100,0,id,0,0)
app.sleep(0.4)
assert(events.emit("workshop:battery.interact",0,100,0,0))
app.tick()
assert(hud.is_open("vcts:panel"), "overlay did not open")
local panel = gui.get_env("vcts:panel")
assert(panel.document.action_1.exists and panel.document.action_2.exists)
panel.action(1)
app.tick()
assert(not panel.document.action_1.enabled, "charge button must be disabled while charging")
app.sleep_until(function() return block.get_field(0,100,0,"stored")==10 end,10000,10)
app.tick() -- Give the graphical client another frame before inspecting the label.
assert(panel.document.summary.text:find("10 / 100",1,true), "UI did not refresh: " .. panel.document.summary.text)
assert(panel.document.action_2.enabled)
panel.action(2)
assert(block.get_field(0,100,0,"stored")==0)
panel.action(1)
panel.close_panel()
app.sleep_until(function() return block.get_field(0,100,0,"stored")==10 end,10000,10)
assert(events.emit("workshop:battery.interact",0,100,0,0))
print("VCTS_UI_READY")
app.sleep(45)
block.destruct(0,100,0,0)
app.tick()
assert(not hud.is_open("vcts:panel"), "overlay outlived its block")
app.close_world(true)
print("VCTS_UI_PASS")
