app.reconfig_packs({"workshop"}, {})
app.new_world("vcts-test", "42", "core:default")
local pid = player.create("VCTS")
app.set_setting("chunks.load-distance", 3)
app.set_setting("chunks.load-speed", 8)
player.set_spawnpoint(pid, 0, 100, 0)
player.set_pos(pid, 0, 100, 0)
app.sleep_until(function() return block.get(0,100,0) ~= -1 end, 10000, 15)
local core = require("vcts:core")
local id = block.index("workshop:battery")
assert(id > 0)
local function place(x)
    block.place(x,100,0,id,0,pid)
    app.tick()
end
local function interact(x)
    assert(events.emit("workshop:battery.interact",x,100,0,pid))
end
local function stored(x) return block.get_field(x,100,0,"stored") end
place(0)
place(2)
assert(stored(0)==0 and stored(2)==0, "initial fields")
interact(0)
core.click(1)
assert(core.snapshot(0,100,0).charging)
core.close_panel(false)
app.sleep_until(function() return stored(0)==10 end, 10000, 10)
assert(stored(2)==0, "instances must be independent")

interact(0)
core.click(2)
assert(stored(0)==0)
for i=1,3 do core.click(1) end
assert(core.stats().pending==1, "duplicate charge")
block.destruct(0,100,0,pid)
place(0)
app.sleep(2.2)
assert(stored(0)==0, "old timer changed replacement")
assert(not core.stats().panel, "removed owner retained its panel")

interact(2)
-- Exercise the presentation subscription without a graphical window.
-- This verifies adapter updates, not VC XML layout/rendering.
local document = {title={}, summary={}, action_1={}, action_2={},
    buttons={clear=function() end, add=function() end}}
core.mount_panel(document)
assert(document.summary.text:find("0 / 100",1,true))
core.click(1)
assert(not document.action_1.enabled and not document.action_2.enabled)
app.sleep_until(function() return stored(2)==10 end, 10000, 10)
assert(document.summary.text:find("10 / 100",1,true), "presentation did not refresh")
assert(document.action_1.enabled and document.action_2.enabled)
core.click(1)
app.save_world()
app.close_world(true)
assert(core.stats().pending==0 and core.stats().instances==0, "world cleanup")
app.open_world("vcts-test")
player.set_pos(pid,0,100,0)
app.sleep_until(function() return block.get(2,100,0) ~= -1 end,10000,15)
core = require("vcts:core")
assert(stored(2)==10, "saved state")
interact(2)
assert(not core.snapshot(2,100,0).charging, "transient charge survived reload")
app.sleep(2.2)
assert(stored(2)==10, "old world timer leaked")

-- Exercise a real chunk unload, not only a manually invoked removed event.
core.click(1)
player.set_pos(pid,5000,100,5000)
app.sleep_until(function() return block.get(2,100,0)==-1 end,10000,20)
assert(core.snapshot(2,100,0)==nil, "unloaded block retained instance")
assert(core.stats().pending==0 and not core.stats().panel, "unload did not dispose work")
player.set_pos(pid,0,100,0)
app.sleep_until(function() return block.get(2,100,0) ~= -1 end,10000,20)
assert(stored(2)==10, "unload changed saved charge")
app.close_world(true)
print("VCTS_INTEGRATION_PASS")
