const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const { buildDemo } = require("./build-demo.cjs");
const { resolveRuntime } = require("./vc-runtime.cjs");
const root = path.resolve(__dirname, "..");
const runtime = resolveRuntime();
const mode = process.argv[2] || "test";
if (!["test", "preview", "play"].includes(mode)) throw new Error("Expected test, preview or play");
const project = buildDemo();
// Always a private user directory: no access to the user's normal worlds/config.
const user = mode === "play" ? path.join(root, "build/demo-user")
  : fs.mkdtempSync(path.join(os.tmpdir(), "vcts-engine-"));
fs.mkdirSync(user, {recursive:true});
const executable = runtime.executable;
const args = ["--res", runtime.resources, "--dir", user, "--project", project];
if (mode !== "play") args.push("--script", path.join(root, `demo/${mode}.lua`));
if (mode === "test") args.push("--headless");
console.log(`Isolated user directory: ${user}`);
console.log(`Runtime: ${executable}`);
const run = spawnSync(executable, args, {cwd:user, encoding:"utf8", timeout: mode === "test" ? 120000 : undefined, maxBuffer:16*1024*1024});
const logDir = path.join(root,"build/logs");
fs.mkdirSync(logDir,{recursive:true});
fs.writeFileSync(path.join(logDir, `${mode}.log`), (run.stdout || "") + (run.stderr || ""));
process.stdout.write(run.stdout || "");
process.stderr.write(run.stderr || "");
const marker = mode === "test" ? "VCTS_INTEGRATION_PASS" : "VCTS_UI_PASS";
const engineErrors = /^\[E\]/m.test((run.stdout || "") + (run.stderr || ""));
const passed = !run.error && run.status === 0 && !engineErrors && (mode === "play" || (run.stdout || "").includes(marker));
if (mode !== "play") fs.rmSync(user,{recursive:true,force:true});
if (run.error) console.error(run.error.message);
if (!passed) process.exitCode = 1;
