app.config_packs({"starter"})
app.new_world("vcts-smoke","42","core:default")
app.sleep(0.25)
app.save_world()
local first=json.parse(file.read("world:starter-state.json"))
assert(first.version==1 and first.data.ticks>0,"typed lifecycle/scheduler/save did not run")
app.close_world(true)
app.open_world("vcts-smoke")
app.save_world()
local second=json.parse(file.read("world:starter-state.json"))
assert(second.data.ticks>=first.data.ticks,"saved state not restored")
file.write("world:probe.json",json.tostring({cases={"world callbacks","typed events","scoped timer","versioned save","world reload"},ticks=second.data.ticks,kind="mod"}))
app.close_world(true)
print("VCTS_PROJECT_PASS")
